name: build asciidoc

on:
  workflow_call:
  push:
    branches:
      - master
jobs:
  asciidoc_build:
    runs-on: ubuntu-latest
    name: Build Asciidoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: time
        run: |
          echo ::set-output name=date::$(TZ=Zulu date "+%Y-%m-%dTZ")
        shell: bash

      - name: Build HTML
        uses: avattathil/asciidoctor-action@master
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          program: "asciidoctor -D . --backend=html5 -o James-Strong-Resume-${{ steps.time.outputs.date }}.html RESUME.adoc"

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v1
        env:
          TIME: ${{ steps.time.outputs.date }}
        with:
          name: James-Strong-Resume-${{ env.TIME }}
          path: James-Strong-Resume--${{ env.TIME }}.html

      - name: Build PDF
        uses: avattathil/asciidoctor-action@master
        env:
          TIME: ${{ steps.time.outputs.date }}
        with:
          program: "asciidoctor-pdf -a allow-uri-read -D . James-Strong-Resume-${{ env.TIME }}.pdf RESUME.adoc"

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        env:
          TIME: ${{ steps.time.outputs.date }}
        with:
          name: James-Strong-Resume-${{ env.TIME }}
          path: James-Strong-Resume-${{ env.TIME }}.pdf
